### PR TITLE
making email password secret

### PR DESCRIPTION
**Pull request by BalazsiOliver**

### CODE REVIEW

**Comment by markkovari** [comment]
Well this is a step in the right direction, but this is not really solving the exposure.

If you would add this to the docker compose as an `env_file` reference it will probably solve this.

https://docs.docker.com/compose/environment-variables/set-environment-variables/#use-the-env_file-attribute

Instead of committing the secret you should distribute it to places where it will run.

Locally: there should be an ignored (by git) `.env`, which contains the value in the following format:
```env
SPRING_MAIL_PASSWORD="whatever secret you have"
```


and if you are referencing it in the correct service of the docker compose file it will be present for the container.

On cloud providers (currently railway): you need to add this as any other environment variable.

Another heads-up: it won't cut just to remove the current secret. You need to rotate it (=revoke the current and create another one).

**Comment by markkovari** [comment]
@BalazsiOliver almost there, you still committed the secret 🙀 .
You ignored the exact `.env` file, but created a `mailPassword.env` (which are not the same) when it comes to the [glob-like pattern](https://en.wikipedia.org/wiki/Glob_(programming)) that git is using to ignore files.

You rather should create a `.env.sample` which you commit without the secret.
And everyone should somehow - safely/securely of course - acquire the password again and copy paste it into. 

After that it will be no longer committed due to the ignored `.env`.

**Comment by markkovari** [comment]
You are at the finish line, only 2 remaining pieces.

1. The syntax of the `.env` files is the following:
```env
KEY1=value
KEY2="some other value"
```

2. We wanted to use the - not committed secret file - the `.env` instead of the sample file in the docker compose. The sample file is usually filled with empty values or invalid credentials, maybe with the local values.

3. (Optional) 
It would be great to let you fellow developers
a. know about these changes - since it is a "breaking change" - with this they need to modify their values too
b. to setup some sort of guideline or documentation how to do that or what to do if this change will be merged.

image

**Comment by BalazsiOliver** [comment]
Is it good to set up the guideline or documentation in the README or is
there a more professional way to share this information with them?

Márk Kővári ***@***.***> ezt írta (időpont: 2024. júl. 26.,
P, 7:24):

**Review by markkovari — APPROVED** [review]
Looking good! 💪 And to answer your question there might be other ways to share how to get this and setup, but this is more then enough as a developer documentation.

**Comment by markkovari** [comment]
closes #23

**Comment by markkovari** [comment]
And you can use this to reference (and even close) other GitHub issues ->
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

**Comment by markkovari** [comment]
closes #23 

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

you can use these too, when merged this should close the issue

**Comment by BalazsiOliver** [comment]
Thank you for your help!

Márk Kővári ***@***.***> ezt írta (időpont: 2024. júl. 27.,
Szo, 5:37):

**Review by agisulyok — APPROVED** [review]

**Pull request merged**
